### PR TITLE
Add scrollbars to Job Results

### PR DESCRIPTION
**Pull request by Mari-Hayashi**
Added scroll bars to the following pages:
1. Professor job dashboard
2. Student job search
3. Student job dashboard

[
postedjobs_scroll
](url)

### CODE REVIEW

**Comment by johan1505** [comment]
Question. If the description of the job is really long, like in the image below. Did you expect the page to be displayed like this? Like all the job previews at the top.

image

**Comment by Mari-Hayashi** [comment]
> Question. If the description of the job is really long, like in the image below. Did you expect the page to be displayed like this? Like all the job previews at the top.
> 
> image

Yeah.
Do you think of any other ways we can do this? I think we can also add a scroll bar to the description.

**Comment by johan1505** [comment]
> > Question. If the description of the job is really long, like in the image below. Did you expect the page to be displayed like this? Like all the job previews at the top.
> > image
> 
> Yeah.
> Do you think of any other ways we can do this? I think we can also add a scroll bar to the description.

I think we can increase the number of jobs that are displayed on the left  I think you have to increase the height of the HTML element that you gave the overflow property, not sure though). In your example, I think the job descriptions only had one sentence, but in reality, those descriptions will be much longer. So, displaying more jobs will fill out that potential empty space below the jobs that I showed in my example.

**Comment by Mari-Hayashi** [comment]
> > > Question. If the description of the job is really long, like in the image below. Did you expect the page to be displayed like this? Like all the job previews at the top.
> > > image
> > 
> > 
> > Yeah.
> > Do you think of any other ways we can do this? I think we can also add a scroll bar to the description.
> 
> I think we can increase the number of jobs that are displayed on the left I think you have to increase the height of the HTML element that you gave the overflow property, not sure though). In your example, I think the job descriptions only had one sentence, but in reality, those descriptions will be much longer. So, displaying more jobs will fill out that potential empty space below the jobs that I showed in my example.

How many jobs do you think we should display in the scroll view?

**Comment by johan1505** [comment]
> > > > Question. If the description of the job is really long, like in the image below. Did you expect the page to be displayed like this? Like all the job previews at the top.
> > > > image
> > > 
> > > 
> > > Yeah.
> > > Do you think of any other ways we can do this? I think we can also add a scroll bar to the description.
> > 
> > 
> > I think we can increase the number of jobs that are displayed on the left I think you have to increase the height of the HTML element that you gave the overflow property, not sure though). In your example, I think the job descriptions only had one sentence, but in reality, those descriptions will be much longer. So, displaying more jobs will fill out that potential empty space below the jobs that I showed in my example.
> 
> How many jobs do you think we should display in the scroll view?
I would say display  5 - 7 jobs, but I think the number of jobs we get from the db is 5, so maybe let's make those job components ask for 13 - 15 jobs to the server maybe? What do you think?

**Comment by johan1505** [comment]
> > > > Question. If the description of the job is really long, like in the image below. Did you expect the page to be displayed like this? Like all the job previews at the top.
> > > > image
> > > 
> > > 
> > > Yeah.
> > > Do you think of any other ways we can do this? I think we can also add a scroll bar to the description.
> > 
> > 
> > I think we can increase the number of jobs that are displayed on the left I think you have to increase the height of the HTML element that you gave the overflow property, not sure though). In your example, I think the job descriptions only had one sentence, but in reality, those descriptions will be much longer. So, displaying more jobs will fill out that potential empty space below the jobs that I showed in my example.
> 
> How many jobs do you think we should display in the scroll view?


I would say display 5 - 7 jobs, but I think the number of jobs we get from the db is 5, so maybe let's make those job components ask for 13 - 15 jobs to the server maybe? What do you think?

I think we can display 6 jobs and get 13-15 jobs per page.

**Comment by johan1505** [comment]
> > > > > Question. If the description of the job is really long, like in the image below. Did you expect the page to be displayed like this? Like all the job previews at the top.
> > > > > image
> > > > 
> > > > 
> > > > Yeah.
> > > > Do you think of any other ways we can do this? I think we can also add a scroll bar to the description.
> > > 
> > > 
> > > I think we can increase the number of jobs that are displayed on the left I think you have to increase the height of the HTML element that you gave the overflow property, not sure though). In your example, I think the job descriptions only had one sentence, but in reality, those descriptions will be much longer. So, displaying more jobs will fill out that potential empty space below the jobs that I showed in my example.
> > 
> > 
> > How many jobs do you think we should display in the scroll view?
> 
> I would say display 5 - 7 jobs, but I think the number of jobs we get from the db is 5, so maybe let's make those job components ask for 13 - 15 jobs to the server maybe? What do you think?
> 
> I think we can display 6 jobs and get 13-15 jobs per page.

Alright. Try that and attach a picture. Thanks!

**Pull request closed without merging**
